[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]

remappings = [
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    "@chainlink/contracts-ccip/=node_modules/@chainlink/contracts-ccip/"
]
